# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gregory Bonaert
email: harokb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Become a better developer and learn computer science through posts with lots of example, clear code and some maths (but not too much)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bonaert.tk" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  harokb

# Build settings
markdown: kramdown
